
<div id="multipleNumbersHeader">
	<h3>T&eacute;rminos  y Condiciones Contenidos Digitales</h3>
</div>
<div id="multipleNumbersMsg">
		<p>Los siguientes t&eacute;rminos  y condiciones deber&aacute;n ser le&iacute;dos atentamente y aceptados en un todo por los clientes  de Nextel Communications Argentina SA (Nextel) interesados en acceder, adquirir  y usar Ringtones, Wallpapers, Juegos y Aplicaciones (en adelante denominados indistintamente  cada uno de ellos como &ldquo;Contenido&rdquo; y/o &ldquo;Contenidos&rdquo; y/o &ldquo;Contenidos Digitales&rdquo;)  y como condici&oacute;n previa a ello.</p>
		<p>&nbsp;</p>
		<p>El cliente  entiende y acepta que la adquisici&oacute;n y uso de Contenidos Digitales implica la plena conformidad y  aceptaci&oacute;n sin ning&uacute;n tipo de reserva a los siguientes t&eacute;rminos y condiciones espec&iacute;ficos  que rigen Contenidos Digitales y de tal modo se complementan en todo aquello en lo que &eacute;stos no los  modifiquen, con los vigentes de Nextel para su Servicio Radioel&eacute;ctrico de  Concentraci&oacute;n de Enlaces y con los dem&aacute;s servicios de telecomunicaciones de los  que Nextel sea su prestador.</p>
		<ol type="1">
			<li>Los Contenidos       Digitales est&aacute;n disponibles para clientes de Nextel prepagos y postpagos       (&eacute;stos &uacute;ltimos deber&aacute;n realizar dichas operaciones mediante el ingreso del       Pin Maestro cuando posean cuatro equipos o m&aacute;s en su cuenta). Dicho       servicio permite al cliente acceder y adquirir Contenidos Digitales para       descarga exclusivamente en su equipo Nextel compatible y hacer uso &uacute;nicamente       desde dicho equipo y dentro del &aacute;rea de cobertura de Nextel en la       Rep&uacute;blica Argentina. No todos los Contenidos Digitales son aptos o       compatibles con la totalidad de los modelos de equipos de la red Nextel. Antes       de aceptar la compra &nbsp;de cualquier       Contenido Digital, el cliente deber&aacute; verificar que su equipo sea apto o       compatible con el Contenido Digital que desea descargar, ingresando en el       sitio web http://<u><a href="http://www.nextel.com.ar/">www.nextel.com.ar</a></u> (en adelante el &ldquo;Sitio&rdquo;).</li>
			<li>El acceso y adquisici&oacute;n de los       Contenidos Digitales podr&aacute; realizarse a trav&eacute;s del ingreso al portal WAP       (wireless application protocol) del equipo bajo el nombre &ldquo;ZONA NEXTEL&rdquo; o a       trav&eacute;s de Internet ingresando en el Sitio. Los Contenidos Digitales se       descargar&aacute;n desde el mismo equipo d&oacute;nde se almacenen. &nbsp;</li>
			<li>El cliente reconoce       que la reproducci&oacute;n en forma o modo alguno, copia, modificaci&oacute;n, inclusi&oacute;n,       distribuci&oacute;n, comercializaci&oacute;n, descompilaci&oacute;n, desensamblado, utilizaci&oacute;n       de t&eacute;cnicas de ingenier&iacute;a inversa de cualquiera de los Contenidos       Digitales integrados y ofrecidos dentro del portal WAP y/o del Sitio, se       encuentra prohibida y constituye una infracci&oacute;n de los derechos de       propiedad intelectual, oblig&aacute;ndose, en consecuencia, a no realizar ninguna       de las acciones mencionadas. La licencia de uso otorgada para la descarga       de los Contenidos Digitales proh&iacute;be la reproducci&oacute;n total o parcial en cualquier       otro soporte de los Contenidos, as&iacute; como la copia privada para su venta.       La copia descargada es exclusivamente para uso recreativo y personal y no       comercial del cliente que la descargue.</li>
			<li>Todas las       marcas, nombres de productos, nombres de las empresas y los logotipos que       aparecen en el Sitio de Nextel, pertenecen a sus respectivos propietarios.       Los clientes no podr&aacute;n copiar o usar las marcas, los nombres de los       productos y los nombres de las empresas, as&iacute; como sus respectivos       logotipos y cualquier otro del cual deriven derechos de autor y/o derechos       de propiedad intelectual o industrial. Los Contenidos Digitales incluidos       en el Sitio est&aacute;n protegidos por la legislaci&oacute;n sobre derechos de autor y       derechos de propiedad intelectual o industrial correspondientes, por lo       que cualquier uso no autorizado puede infringir dichos derechos, marcas       registradas u otras leyes aplicables. El cliente se compromete a       respetar los presentes t&eacute;rminos y condiciones, siendo el &uacute;nico responsable       de su incumplimiento frente a terceros, y dejar&aacute; en todo caso indemne a       Nextel frente a cualquier reclamo que pudiera originarse, incluyendo los       derechos de copyright, marcas, patentes, informaci&oacute;n confidencial y       cualquier otro derecho de propiedad intelectual o industrial, frente a       estos como consecuencia de ello. </li>
			<li>El cliente       se obliga a usar los Contenidos Digitales de buena fe, de forma diligente,       correcta y l&iacute;cita y, en particular, se compromete a abstenerse de utilizar       los Contenidos Digitales de forma, con fines o efectos contrarios a la       ley, a la moral y a las buenas costumbres generalmente aceptadas o al       orden p&uacute;blico. </li>
			<li>El cliente entiende       y acepta que las muestras de los Contenidos a las que acceda a       trav&eacute;s del Sitio, pueden o&iacute;rse y/o verse distinto una vez descargado en su       equipo, variando esto seg&uacute;n la capacidad y funcionalidad t&eacute;cnica del mismo.       Estas muestras son solo orientativas y forman parte de la informaci&oacute;n       puesta a disposici&oacute;n de los clientes en relaci&oacute;n a las caracter&iacute;sticas       propias de los Contenidos Digitales ofrecidos. </li>
			<li>El cliente entiende       y acepta que mientras haga uso del modo telef&oacute;nico y/o de conexi&oacute;n       directa, el equipo no estar&aacute; en condiciones t&eacute;cnicas de hacer uso de los       servicios de Contenido. De igual manera, mientras est&eacute; usando la red de       datos, puede bloquear el ingreso de comunicaciones en modo telefon&iacute;a y/o       conexi&oacute;n directa. </li>
			<li>Los precios       de los Contenidos Digitales disponibles ser&aacute;n los vigentes al tiempo de la       compra, y que en tal sentido se encuentran publicados en el Sitio al       momento de la operaci&oacute;n y se comunican al cliente en el portal WAP del       equipo previo a la aceptaci&oacute;n de la compra y descarga del Contenido. Dichos       precios se encuentran gravados por el impuesto al valor agregado. El       tr&aacute;fico de datos que sea generado al navegar por el portal WAP y durante       la descarga del Contenido al equipo donde se almacene es sin cargo para el       cliente. </li>
			<li>La modalidad de contrataci&oacute;n de los       Contenidos Digitales podr&aacute; ser: (i) Cargo por &uacute;nica vez (uso ilimitado);       (ii) Cargo mensual (suscripci&oacute;n mensual). Ello depender&aacute; del tipo de       Contenido, sobre el cual aplicar&aacute; una u otra modalidad, siendo informado de       ello el Cliente previo a &nbsp;concretar       la compra del Contenido que desee adquirir. Bajo la modalidad de contrataci&oacute;n       mensual, el acceso se habilitar&aacute; por treinta (30) d&iacute;as corridos, contados       a partir del d&iacute;a en que se efectu&oacute; la suscripci&oacute;n.&nbsp;&nbsp;&nbsp;&nbsp; </li>
			<li>La modalidad de pago del Contenido Digital       adquirido por parte del cliente depender&aacute; del plan comercial y/o modalidad       previamente contratada con Nextel, a saber: (i) plan comercial pospago, el       precio de cada Contenido adquirido ser&aacute; facturado en el ciclo de       facturaci&oacute;n inmediato posterior a su adquisici&oacute;n; (ii) plan comercial       &ldquo;STOP/REGIONALES&rdquo; (cualesquiera de ellos), el precio de cada Contenido       adquirido podr&aacute; ser, a elecci&oacute;n del cliente, facturado en el ciclo de       facturaci&oacute;n inmediato posterior a su adquisici&oacute;n o debitado autom&aacute;ticamente       del cr&eacute;dito del abono del plan comercial STOP/REGIONALES contratado/s y/o       de su cr&eacute;dito prepago -para el supuesto que&nbsp; hubiera adquirido tal y contin&uacute;e operando en modalidad       prepaga-; y (iii) modalidad prepaga: el precio de cada Contenido adquirido       ser&aacute; debitado autom&aacute;ticamente de su cr&eacute;dito prepago (debiendo contar con       un saldo prepago m&iacute;nimo equivalente al valor del Contenido). </li>
			<li>El alcance       geogr&aacute;fico de uso de los Contenidos Digitales desde los equipos Nextel       compatibles ser&aacute; el comprendido dentro del &aacute;rea de cobertura de la red de       Nextel (dicha &aacute;rea de cobertura puede consultarse en <a href="http://www.nextel.com.ar/cobertura" title="http://www.nextel.com.ar/cobertura">www.nextel.com.ar/cobertura</a>). </li>
			<li>Nextel podr&aacute; a su       s&oacute;lo criterio en cualquier momento modificar los presentes t&eacute;rminos y/o suspender       total o parcialmente, temporal o definitivamente la distribuci&oacute;n de       Contenidos Digitales, no teniendo ning&uacute;n tipo de responsabilidad por       pasibles da&ntilde;os y/o perjuicios que pudieran derivarse. Nextel       se reserva el derecho a denegar sin previo aviso el acceso a sus clientes       cuando &eacute;stos hagan un uso indebido o inconveniente y/o perjudique su       normal desarrollo sin que ello genere responsabilidad alguna de Nextel ni       derecho a reclamo alguno. Nextel no garantiza la exactitud ni el acceso       ininterrumpido de los Contenidos Digitales ofrecidos en el portal WAP y en       el Sitio. </li>
			<li>El cliente entiende       y acepta que dadas las implicancias t&eacute;cnicas del servicio, podr&iacute;an       verificarse en el mismo eventuales limitaciones parciales y/o totales en       su navegaci&oacute;n, seg&uacute;n sus facilidades tecnol&oacute;gicas; y asimismo, que se       sirve de los Contenidos Digitales distribuidos y propuestos -conforme los       accesos disponibles- y m&aacute;s all&aacute; de la informaci&oacute;n puesta a su disposici&oacute;n       en relaci&oacute;n a las caracter&iacute;sticas propias de los Contenidos Digitales       ofrecidos, bajo su propia responsabilidad y a su propio riesgo. </li>
			<li>Nextel tampoco ser&aacute;       responsable del inadecuado funcionamiento del Sitio si ello obedece a       labores de mantenimiento, a una defectuosa configuraci&oacute;n de los equipos       por parte del cliente o a su insuficiente capacidad para soportar los       sistemas indispensables para poder hacer uso de los Contenidos, ni por       ning&uacute;n da&ntilde;o que se genere al cliente en caso de imposibilidad de acceder a       los Contenidos Digitales debido a supuestos de caso fortuito, fuerza mayor       u otras causas no imputables a &eacute;sta. </li>
			<li>Nextel no otorga       garant&iacute;as respecto a la adquisici&oacute;n y uso de los Contenidos Digitales, ni       sobre ning&uacute;n software o hardware utilizado. En ning&uacute;n caso Nextel ser&aacute;       responsable por los       da&ntilde;os que se deriven de su utilizaci&oacute;n, ni por lucro cesante o da&ntilde;o       emergente o por da&ntilde;o directos o indirectos, especiales o no, ni por       p&eacute;rdida econ&oacute;mica, injurias personales o da&ntilde;os reclamados por el cliente o       cualquier tercero, limit&aacute;ndose la responsabilidad total y por todo       concepto de Nextel como m&aacute;ximo a la suma efectivamente cobrada por &eacute;sta       del cliente por la adquisici&oacute;n de Contenidos, salvo que la ley disponga un       tratamiento distinto.</li>
			<li>Algunos de los Contenidos Digitales       disponibles pueden incluir muestras gr&aacute;ficas, visuales y descripciones de       desnudez. Si por cualquier motivo el cliente considera       que este tipo de Contenido puede afectar su       susceptibilidad, deber&aacute; evitar su adquisici&oacute;n y descarga y en tal       sentido acepta que Nextel no ser&aacute; responsable frente a &eacute;ste del Contenido       que pueda considerarse ofensivo o censurable.</li>
			<li>Soporte t&eacute;cnico       telef&oacute;nico o       personalizado en cualquier sucursal Nextel, de lunes a viernes (d&iacute;as       h&aacute;biles) de 9 a 18 horas. Nextel no brinda asistencia, atenci&oacute;n, ni soporte       a domicilio. En ning&uacute;n       caso la asistencia telef&oacute;nica o personalizada por parte de Nextel,       comprende ni comprender&aacute; los Contenidos Digitales que el cliente no haya       descargado e instalado conforme las condiciones, limitaciones y a trav&eacute;s       de los procedimientos que &eacute;sta disponga, los que ser&aacute;n a propia discreci&oacute;n       y riesgo del cliente qui&eacute;n ser&aacute; el &uacute;nico responsable por cualquier da&ntilde;o a       su equipo o por la p&eacute;rdida de informaci&oacute;n que resulte de descargar dichos       Contenidos Digitales o material o datos sin respetar las presentes       condiciones y/o las que se le informen en el futuro, quedando facultada Nextel a bloquear y/o       inhabilitar el servicio respectivo sin previo aviso, as&iacute; como a suspender       la Garant&iacute;a Contractual &ndash;en caso de corresponder- en dicho supuesto. </li>
			<li>El cliente conoce y       entiende que los Contenidos Digitales se descargar&aacute;n desde el mismo equipo       donde se almacenen y, en tal sentido dejar&aacute;n de estar disponible en caso       de cambio de equipo, desapoderamiento o destrucci&oacute;n del mismo, no       encontr&aacute;ndose amparados por ende, bajo las Garant&iacute;as Contractuales       ofrecidas por Nextel, el traspaso de los Contenidos Digitales al nuevo       equipo.</li>
			<li>La descarga de       Contenidos Digitales est&aacute; sujeta a la capacidad del equipo del cliente. Se       podr&aacute;n descargar tantos Contenidos Digitales seg&uacute;n admita en cantidad y       calidad la memoria del equipo d&oacute;nde se descargan y almacenan. Si el equipo       Nextel no tiene memoria disponible suficiente para descargar un Contenido       Digital adquirido, el cliente deber&aacute; liberar &nbsp;espacio en la memoria del equipo e intentar la descarga       nuevamente, la que no tendr&aacute; costo adicional alguno.</li>
			<li>Los presentes       t&eacute;rminos y condiciones no excluyen la posibilidad de que ciertos       Contenidos Digitales ofrecidos por Nextel se sometan a condiciones       especiales de uso, las cuales, deber&aacute;n ser consultadas y aceptadas por el       cliente en forma previa a su adquisici&oacute;n. </li>
			<li>Para mayor       informaci&oacute;n sobre Contenidos Digitales podr&aacute; consultar a trav&eacute;s de       Internet ingresando al Sitio o comunicarse gratuitamente desde su equipo       Nextel al *611 o al 0800-199-3983 o con cargo al Centro de Atenci&oacute;n       al Cliente (011) 5359-0000 durante las 24 horas del d&iacute;a. </li>
		</ol>
</div>

<p class="submitMultipleNumbers">
	<a href="javascript:void 0;" onclick="ajaxLoader('popup_multiple_number_failed.jsp','popupContentArea');"><img src="images/cm/btn_accept.gif" alt="Aceptar" /></a>
	<a href="popup_multiple_number.jsp?u=in"><img src="images/cm/btn_cancel.gif" alt="Cancelar"/></a>
	<a href="javascript:void 0;" onclick="window.parent.tb_remove();"><img src="images/cm/btn_exit.gif" alt="Salir"/></a>
</p>
