<%@ include file = "../template/nextelch/tools.jsp" %>

<div id="common" class="content">

	<div id="common_right_bg"> </div>
	<jsp:include page="../template/nextelch/survey.jsp" flush="true"></jsp:include>	
	
	<div id="common_header">
		<h2>Términos y Condiciones Contenidos Digitales</h2>
		<span class="total"></span>
	</div>
	
	<div id="common_body">
		<ul>
			<li>Est&aacute; prohibida la modificaci&oacute;n, copia, reproducci&oacute;n, inclusi&oacute;n,       distribuci&oacute;n, en otros servidores o cualquier otro tipo de soporte, total       o parcial de los contenidos digitales (los &ldquo;Contenidos Digitales&rdquo;) comercializados       por Nextel del Per&uacute; S.A. (&ldquo;NEXTEL&rdquo;) sin la expresa y previa autorizaci&oacute;n por       escrito por parte de NEXTEL. </li>
			<li>La licencia otorgada para la descarga de los Contenidos Digitales       proh&iacute;be la reproducci&oacute;n total o parcial del Contenido Digital descargado, as&iacute;       como la copia privada para su venta. La copia descargada de los Contenidos       Digitales es exclusivamente para uso privado del cliente de NEXTEL que la       descargue (el &ldquo;Cliente&rdquo;). </li>
			<li>El Cliente reconoce que la reproducci&oacute;n, copia, modificaci&oacute;n,       distribuci&oacute;n, comercializaci&oacute;n, descompilaci&oacute;n, desensamblado, utilizaci&oacute;n       de t&eacute;cnicas de ingenier&iacute;a inversa o de cualquier otro medio para obtener       el c&oacute;digo fuente, transformaci&oacute;n o publicaci&oacute;n de cualquier resultado de       pruebas de referencias no autorizadas de cualquiera de los Contenidos       Digitales integrados y ofrecidos dentro del sitio de NEXTEL constituye una       infracci&oacute;n de los derechos de propiedad intelectual, oblig&aacute;ndose, en       consecuencia, a no realizar ninguna de las acciones mencionadas.</li>
			<li>El Cliente se abstendr&aacute; de llevar a cabo cualquier conducta en el       uso del sitio de NEXTEL y de los Contenidos Digitales ofrecidos en el       mismo que atente contra los derechos de propiedad intelectual o industrial       de NEXTEL y de terceros, y/o que vulnere y/o transgreda el honor, la intimidad       personal y/o familiar y/o la imagen de terceros, y/o que sean il&iacute;citos y/o       atenten a la moralidad, y dejar&aacute; en todo caso indemne a NEXTEL frente a       cualquier reclamo, judicial o extrajudicial que se presente frente a estos       como consecuencia de dicho uso. </li>
			<li>NEXTEL no ser&aacute; responsable por los da&ntilde;os y perjuicios de toda       naturaleza que pudieran originarse como consecuencia de la descarga y uso       de los Contenidos Digitales, incluyendo los derechos de copyright, marcas,       patentes, informaci&oacute;n confidencial y cualquier otro derecho de propiedad       intelectual o industrial que se derive de ello.</li>
			<li>El Cliente acepta que en determinadas circunstancias no podr&aacute;       acceder al sitio web de NEXTEL como consecuencia de la realizaci&oacute;n de       labores de mantenimiento. Durante el plazo de ejecuci&oacute;n de dicha labores       el Cliente no podr&aacute; descargar adecuadamente los Contenidos Digitales. La       adecuada descarga de Contenidos Digitales se realizar&aacute; en los equipos       NEXTEL detallados en el sitio web de NEXTEL. </li>
			<li>El Cliente se abstendr&aacute; de llevar a cabo por medio del uso de los       Contenidos Digitales cualquier destrucci&oacute;n, alteraci&oacute;n, inutilizaci&oacute;n o       da&ntilde;os de los datos, programas o documentos electr&oacute;nicos pertenecientes a       NEXTEL, a sus proveedores y/o a terceros, as&iacute; como de introducir y/o       difundir en la red de datos de NEXTEL &ldquo;programas&rdquo;, &ldquo;virus&rdquo;, &ldquo;applets&rdquo;,       &ldquo;controles Active X&rdquo; y/o cualquier instrumento y/o dispositivo f&iacute;sico y/o       electr&oacute;nico que causen y/o sean susceptibles de causar cualquier tipo de       alteraci&oacute;n en la red de datos de NEXTEL, en sus sistemas, y/o en los       equipos de terceros. Asimismo quien realice actividades prohibidas por los       presentes T&eacute;rminos y Condiciones ser&aacute; responsable por las consecuencias       penales y/o civiles que se deriven por dichas actividades. </li>
			<li>El Cliente autoriza a NEXTEL a incluir informaci&oacute;n publicitaria en       los mensajes que le env&iacute;e a su equipo NEXTEL.</li>
			<li>Todas las dem&aacute;s marcas, nombres de productos, nombres de las       empresas y los logotipos que aparecen en el sitio web de NEXTEL,       pertenecen a sus respectivos propietarios o titulares. Los Clientes deben       obtener la autorizaci&oacute;n de ellos para copiar o utilizar las marcas, los       nombres de los productos y los nombres de las empresas, as&iacute; como sus       respectivos logotipos y cualquier otro del cual deriven derechos de autor       y/o derechos de propiedad intelectual. Los Contenidos Digitales est&aacute;n       protegidos por los derechos de autor y derechos de propiedad intelectual o       industrial correspondientes por cada uno de sus propietarios, por lo que       cualquier uso indebido por alg&uacute;n tercero se sujetar&aacute; a lo estipulado en las       normas peruanas sobre la materia. &nbsp;</li>
			<li>El Cliente se obliga a usar los Contenidos Digitales de buena fe,       de forma diligente, correcta y l&iacute;cita y, en particular, se compromete a       abstenerse de utilizar los Contenidos Digitales de forma, con fines o       efectos contrarios a la ley, a la moral y a las buenas costumbres       generalmente aceptadas o al orden p&uacute;blico. </li>
			<li>El Cliente reconoce que NEXTEL no es el titular ni creador de los       Contenidos Digitales y que el servicio que NEXTEL prestar&aacute; al Cliente se       limita a la descarga de tales Contenidos Digitales. &nbsp;En esa medida,       NEXTEL no garantiza la calidad ni la precisi&oacute;n de los Contenidos Digitales       ni que los resultados que los Clientes obtengan del uso de los mismos       responder&aacute; a sus expectativas o se adecuar&aacute;n a un fin espec&iacute;fico.</li>
			<li>Salvo por los casos de dolo, culpa inexcusable o culpa leve, NEXTEL       no puede ser considerado responsable por los posibles da&ntilde;os o p&eacute;rdidas de       cualquier naturaleza que el Cliente considere que ha sufrido como       consecuencia del mal funcionamiento del Contenido Digital ofrecido en la       web o en el portal WAP del equipo NEXTEL, como as&iacute; tambi&eacute;n por la no       recepci&oacute;n de informaci&oacute;n y/o por su inexactitud o por ser &eacute;sta incompleta.       Atendiendo a ello, el Cliente se sirve de los Contenidos Digitales       distribuidos y propuestos a trav&eacute;s del sitio &nbsp;de NEXTEL y en el       portal WAP de su equipo NEXTEL bajo su propia responsabilidad y a su       propio riesgo. </li>
			<li>NEXTEL &uacute;nicamente se responsabiliza y garantiza la calidad del       servicio de descarga de los Contenidos Digitales y que dicho servicio       funcionar&aacute; de conformidad con sus especificaciones t&eacute;cnicas y la       informaci&oacute;n puesta a disposici&oacute;n de los Clientes en relaci&oacute;n al mismo.       Salvo por los casos de dolo, culpa inexcusable o culpa leve, NEXTEL no       ser&aacute; responsable por lucro cesante o da&ntilde;o emergente o por da&ntilde;os directos o       indirectos, especiales o no, ni por p&eacute;rdida econ&oacute;mica, injurias personales       o da&ntilde;os reclamados por el Cliente o cualquier tercero.</li>
			<li>El Cliente acepta conocer que, para la descarga de los Contenidos       Digitales, es necesario que el equipo NEXTEL a trav&eacute;s del cual se realiza       la descarga, sea compatible con el Contenido Digital que solicita       descargar.</li>
			<li>Algunos de los Contenidos Digitales disponibles pueden incluir       muestras gr&aacute;ficas, visuales y descripciones de desnudez, violencia o       material que se considere ofensivo, indecente o censurable. El Cliente       descargar&aacute; los Contenidos Digitales bajo su propio riesgo no siendo       responsable NEXTEL por la descarga de dichos contenidos, bajo ninguna       circunstancia. Si por cualquier motivo el Cliente considera que este tipo       de Contenido puede afectar su susceptibilidad y/o no cumple con el       requisito de edad requerido (mayor de 18 a&ntilde;os), le solicitamos evitar su       descarga.</li>
			<li>Los Clientes que cuenten con planes tarifarios postpago  y que adquieran Contenidos Digitales, ser&aacute;n facturados por los mismos en  d&oacute;lares de los Estados Unidos de Norteam&eacute;rica en su correspondiente recibo de  servicios y podr&aacute;n cancelar los mismos en d&oacute;lares de los Estados Unidos de  Norteam&eacute;rica o en moneda nacional al tipo de cambio que se encuentre vigente el  d&iacute;a de pago, conforme a lo dispuesto por el art&iacute;culo 1237 del C&oacute;digo Civil.</li>
		</ul>
	</div>

</div>
