<%@ include file = "../template/optus/tools.jsp" %>

	<div class="content">
	
		<h2 class="pagetitle"><img src="UI/img/<%=strUI%>/hdr_tc.jpg" alt="Terms and Conditions" /></h2>
	
		<h2 class="breadcrumb">
			<a href="home.jsp?ui=<%=strUI%>">Home</a> &gt;
			Terms of Licence
		</h2>
		
			<div id="contentContainer">
					<p>1. Your use of the Optus My Account application (<b><i>My Account</i></b>) is governed by the  following terms and conditions (<b><i>Agreement</i></b>). If you use My Account,  you agree to be bound by the Agreement. If you do not agree to be bound by the  terms of this Agreement or you do not want to use My Account:</p><p>&nbsp;</p>
							<p>(a) if My Account came pre-installed on your mobile device, you should call Optus  Customer Care on 133 937 and they will  disable it for you; or</p><p>&nbsp;</p>
							<p>(b) if you uploaded My Account to your mobile device, you should delete it.</p><p>&nbsp;</p>
					<p>2. <b>Parties:</b> This Agreement (<b><i>Agreement</i></b>)  is between you, the individual using My Account (<b><i>you</i></b> or <b><i>Your</i></b>)  and Optus Networks Pty Limited (ABN  92 008 570 330) and Optus Mobile Pty Limited (ABN  65 054 365 696) (jointly, <b><i>Optus</i></b>).</p><p>&nbsp;</p>
					<p>3. <b>Scope:</b> You acknowledge that this Agreement applies in addition to the Optus  agreement applicable to Optus' provision of mobile phone services to you (found  at <a href="http://www.optus.com.au/sfoa">www.optus.com.au/sfoa</a>).</p><p>&nbsp;</p>
					<p>4. <b>Licence:</b> Optus grants you a limited,  non-transferable and non-exclusive, revocable personal licence to use My  Account in Australia  on the mobile device on which it was received or uploaded by you, for  non-commercial purposes subject to the terms of this Agreement.   Any upgrade or new release of My Account is  also subject to the provisions of this Agreement.</p><p>&nbsp;</p>
					<p>5. <b>Notifications:</b> As part of your use of  My Account, you consent to Optus sending you push notifications or SMS  relating to the operation of My Account and  Your use of it, details about Your mobile service arrangements with Optus,  including, without limitation, offers available if your mobile agreement is to  expire.</p><p>&nbsp;</p>
					<p>6. <b>Charges:</b>  My Account is provided free of charge to  you as part of Optus' provision of mobile phone services to you.  You will not pay any data download charges  for your ongoing use of My Account, except (i) whilst roaming, in which case  all data use will be charged at the applicable international roaming rate, and  (ii) unless you leave the My Account application and access My Account via a  web browser.  If you are an Optus  pre-paid customer, you must have a minimum balance on your mobile phone service  to access the My Account application. </p><p>&nbsp;</p>
					<p>7. <b>Conditions  of use:</b>  You must not reverse engineer, decompile, disassemble, or extract any element  of and/or otherwise discover any source code, algorithms, methods or techniques  embodied in My Account.  You must not  modify, transfer, distribute, pledge, sublicense, rent, lease, or create  derivative works based on My Account, including its user interfaces.  You must not use My Account for any unlawful  or illegal activity. You must not knowingly take any action that would cause My  Account to be placed in the public domain.</p><p>&nbsp;</p>
					<p>8. <b>Ownership of My Account:</b> You  acknowledge that (i) My Account is protected by intellectual property laws, and  embodies valuable confidential and trade secret information of Optus and its  licensor; (ii) Optus or its licensor retains all right, title and interest in  and to My Account; and (iii) ownership of all patent, copyright, trade secrets  and other intellectual property rights, shall be and remain the sole property  of Optus or its licensor.</p><p>&nbsp;</p>
					<p>9. <b>Modification:</b> Optus may, in its sole  discretion, change, add or remove any part of this Agreement, or any other  terms, features or functionality of My Account at any time.  Any changes in relation to My Account by  Optus shall become part of the Agreement and shall apply immediately.  By continuing to use My Account after any  changes you indicate acceptance of the changes.  If you do not agree to the changes, you  should follow the steps set out at Clause 1 of this Agreement in relation to  deactivation or deletion, as required.</p><p>&nbsp;</p>
					<p>10. <b>Term and Termination:</b> This Agreement  commences when you first use My Account and continues until terminated by  either party.  Optus may terminate this  Agreement in its discretion and cease providing My Account (or any part of it)  at any time.  You may terminate this  agreement and your use of My Account at any time by following the steps set out  at Clause 1 of this Agreement in relation to deactivation or deletion, as  required.</p><p>&nbsp;</p>
					<p>11. <b>Timing/Accuracy:</b> Due to processing  times, recent account activity, including recently made calls or recent data  usage and, for Optus pre-paid customers, recent account recharges, may not  appear in usage details listed in My Account. To obtain the most up-to-date  information available, update My Account after any recent account activity.  Otherwise, the accuracy of the system is updated as is set out on your My  Account screen.</p><p>&nbsp;</p>
					<p>12. <b>Disclaimer:</b> TO THE EXTENT PERMITTED BY LAW, OPTUS DOES NOT  REPRESENT, WARRANT OR GUARANTEE THE SUITABILITY, COMPLETENESS, ACCURACY OR  CURRENCY OF ANY INFORMATION OR CONTENT ACCESSED VIA  MY ACCOUNT OR THAT MY ACCOUNT WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE,  FREE OF VIRUSES OR OTHER HARMFUL  COMPONENTS.</p><p>&nbsp;</p>
					<p>13. <b>Personal  Information and Privacy:</b> Optus will handle any personal information in  accordance with the Optus Privacy Policy. You  acknowledge and agree that You have read our Privacy Policy, which is available  at <a href="http://www.optus.com/privacy">www.optus.com/privacy</a> and is incorporated  in this Agreement by this reference.  You  must ensure your mobile device and any passwords you use in relation to such  devices is kept secure. </p><p>&nbsp;</p>
					<p>14. <b>Contact info:</b> All support relating  to My Account should be directed to Optus at <a href="http://www.optus.com.au/contactus">www.optus.com.au/contactus</a> or at  133 937.</p><p>&nbsp;</p>
			</div>
	</div>
	
