<%@ include file = "../template/nextelar/tools.jsp" %>

<div id="cmBody">

	<div class="textcontent">
		<h2 class="title">T&eacute;rminos  y Condiciones Contenidos Digitales</h2>
		<p>Los siguientes T&eacute;rminos y Condiciones deber&aacute;n ser le&iacute;dos  atentamente y aceptados en un todo por los Clientes interesados en acceder,  adquirir y usar los Ringtones, Wallpapers, Juegos y Aplicaciones (en adelante denominados  &ldquo;Contenido&rdquo; y/o &ldquo;Contenidos&rdquo; y/o &ldquo;Contenidos Digitales&rdquo;) que ofrece Nextel Communications Argentina S.R.L (Nextel). Estos T&eacute;rminos y Condiciones son  espec&iacute;ficos y de tal modo se complementan en todo aquello en lo que &eacute;stos no  los modifiquen, con los vigentes de Nextel para su Servicio Radioel&eacute;ctrico de  Concentraci&oacute;n y Enlaces y con los dem&aacute;s servicios de telecomunicaciones de los  que Nextel sea su prestador.</p>
		<p>Si no est&aacute; de acuerdo con estos t&eacute;rminos y condiciones,  abst&eacute;ngase de acceder, adquirir y usar los Contenidos Digitales ofrecidos por  Nextel. De lo contrario entenderemos que el acceso, adquisici&oacute;n y uso de los  mismos implica el pleno conocimiento y aceptaci&oacute;n sin ning&uacute;n tipo de reservas a  los t&eacute;rminos de contrataci&oacute;n establecidos en el presente documento.</p>
		<p>Los T&eacute;rminos y Condiciones que a continuaci&oacute;n se indican aplican  a todos aquellos Contenidos Digitales puestos a disposici&oacute;n de los Clientes por  medio de cualquier tecnolog&iacute;a presente o futura, como por ejemplo, tecnolog&iacute;a  WAP (wireless application protocol), SMS (short message service) o Internet,  y podr&aacute;n ser actualizadas por NEXTEL peri&oacute;dicamente. El Cliente podr&aacute; consultar  en cualquier momento su &uacute;ltima versi&oacute;n en <a href="http://www.nextel.com.ar/legales/tyc_contenido_digital.php" target="_blank">www.nextel.com.ar/legales/tyc_contenido_digital.php</a></p>
		<ol type="1">
			<li>Los presentes       T&eacute;rminos y Condiciones no excluyen la posibilidad de que ciertos       Contenidos Digitales ofrecidos por NEXTEL se sometan a condiciones       especiales de uso, las cuales, deber&aacute;n ser consultadas y aceptadas por el       Cliente en forma previa a su utilizaci&oacute;n. Esta prohibida la modificaci&oacute;n,       copia, reproducci&oacute;n, inclusi&oacute;n, distribuci&oacute;n, en otros servidores o       cualquier otro tipo de soporte, total o parcial de los Contenidos       Digitales ofrecidos por NEXTEL sin la expresa y previa autorizaci&oacute;n       escrita por parte de NEXTEL. La licencia otorgada para la descarga de los       Contenidos Digitales proh&iacute;be la reproducci&oacute;n total o parcial en otros       soportes de la obra descargada de Internet, as&iacute; como la copia privada para       su venta. La copia descargada es exclusivamente para uso privado del       Cliente que la descargue. </li>
			<li>Los Contenidos       Digitales ofrecidos por NEXTEL a los Clientes no son aptos o compatibles       con la totalidad de los modelos de equipos que NEXTEL comercializa. Antes       de comenzar el proceso de compra de cualquier tipo de Contenido Digital,       verifique que su equipo es apto para el Contenido Digital que desea       contratar en el sitio web arriba indicado. Sin perjuicio de ello, NEXTEL       le avisar&aacute; si su modelo de equipo es incompatible con el Contenido Digital       que desea contratar. </li>
			<li>El Cliente reconoce       que la reproducci&oacute;n, copia, modificaci&oacute;n, distribuci&oacute;n, comercializaci&oacute;n,       descompilaci&oacute;n, desensamblado, utilizaci&oacute;n de t&eacute;cnicas de ingenier&iacute;a       inversa o de cualquier otro medio para obtener el c&oacute;digo fuente,       transformaci&oacute;n o publicaci&oacute;n de cualquier resultado de pruebas de       referencias no autorizadas de cualquiera de los Contenidos Digitales       integrados y ofrecidos dentro del sitio de NEXTEL constituye una       infracci&oacute;n de los derechos de propiedad intelectual, oblig&aacute;ndose, en       consecuencia, a no realizar ninguna de las acciones mencionadas. </li>
			<li>El Cliente se       abstendr&aacute; de llevar a cabo cualquier conducta en el uso del sitio de       NEXTEL y de los Contenidos Digitales ofrecidos en el mismo que atente       contra los derechos de propiedad intelectual o industrial de NEXTEL y de terceros,       o que vulnere o transgreda el honor, la intimidad personal o familiar o la       imagen de terceros, o que sean il&iacute;citos o atenten a la moralidad, y dejar&aacute;       en todo caso indemne a NEXTEL frente a cualquier reclamo, judicial o       extrajudicial que se presente frente a estos como consecuencia de dicho       uso.</li>
			<li>NEXTEL no ser&aacute;       responsable por los da&ntilde;os y perjuicios de toda naturaleza que pudieran       originarse, incluyendo los derechos de copyright, marcas, patentes,       informaci&oacute;n confidencial y cualquier otro derecho de propiedad intelectual       o industrial. &nbsp;&nbsp;&nbsp;</li>
			<li>Todas las       dem&aacute;s marcas, nombres de productos, nombres de las empresas y los       logotipos que aparecen en el sitio de NEXTEL, pertenecen a sus respectivos       propietarios. Los Clientes deben obtener la autorizaci&oacute;n de ellos para       copiar o usar las marcas, los nombres de los productos y los nombres de       las empresas, as&iacute; como sus respectivos logotipos y cualquier otro del cual       deriven derechos de autor y/o derechos de propiedad intelectual. Los       Contenidos Digitales est&aacute;n protegidos por los derechos de autor y derechos       de propiedad intelectual o industrial correspondientes por cada uno de sus       propietarios, por lo que cualquier uso indebido por alg&uacute;n tercero se sujetar&aacute;       a lo estipulado en la Ley de Propiedad Intelectual N&ordm; 11.723 y dem&aacute;s leyes       aplicables. </li>
			<li>El       Cliente se obliga a usar los Contenidos Digitales de buena fe, de forma       diligente, correcta y l&iacute;cita y, en particular, se compromete a abstenerse       de utilizar los Contenidos Digitales de forma, con fines o efectos       contrarios a la ley, a la moral y a las buenas costumbres generalmente       aceptadas o al orden p&uacute;blico. </li>
			<li>El Cliente se       abstendr&aacute; de llevar a cabo por medio del uso de los Contenidos Digitales       cualquier destrucci&oacute;n, alteraci&oacute;n, inutilizaci&oacute;n o da&ntilde;os de los datos,       programas o documentos electr&oacute;nicos pertenecientes a NEXTEL, a sus       proveedores o a terceros, as&iacute; como de introducir o difundir en la Red       &ldquo;programas&rdquo;, &ldquo;virus&rdquo;, &ldquo;applets&rdquo;, &ldquo;controles Active X&rdquo; o cualquier       instrumento o dispositivo f&iacute;sico o electr&oacute;nico que causen o sean       susceptibles de causar cualquier tipo de alteraci&oacute;n en la Red, en el       sistema, o en los equipos de terceros. Igualmente, queda expresamente       prohibida cualquier tipo de actividad o pr&aacute;ctica que transgreda los       principios de buena conducta aceptados generalmente entre los usuarios de       Internet. Asimismo quien realice actividades prohibidas por los presentes       T&eacute;rminos y Condiciones ser&aacute; penal y econ&oacute;micamente responsable por los       da&ntilde;os producidos. </li>
			<li>NEXTEL no ser&aacute;       responsable de ning&uacute;n da&ntilde;o que se genere al Cliente en caso de       imposibilidad de acceder a los Contenidos Digitales objeto de los       presentes T&eacute;rminos y Condiciones debido a supuestos de caso fortuito,       fuerza mayor u otras causas no imputables a &eacute;sta. </li>
			<li>NEXTEL tampoco ser&aacute;       responsable del inadecuado funcionamiento del sitio si ello obedece a       labores de mantenimiento, a una defectuosa configuraci&oacute;n de los equipos por       parte del Cliente o a su insuficiente capacidad para soportar los sistemas       indispensables para poder hacer uso de los Contenidos. </li>
			<li>NEXTEL se reserva       el derecho de incluir en los mensajes que env&iacute;e una breve informaci&oacute;n       publicitaria. </li>
			<li>El Cliente que       acceda al sitio de NEXTEL deber&aacute; tener presente que las       &quot;muestras&quot; de los contenidos (RingTones, Wallpapers, etc.)       pueden o&iacute;rse y verse distinto una vez instalado en su equipo, variando       esto seg&uacute;n el equipo. Estas muestras (archivos WAV, JPG, etc.) son solo       orientativas. </li>
			<li>Impacto de       servicios de datos: mientras el Cliente est&aacute; usando el modo telef&oacute;nico y/o       de conexi&oacute;n directa, el equipo no estar&aacute; en condiciones t&eacute;cnicas de hacer       uso de los servicios de datos. De igual manera, mientras est&eacute; usando la       red de datos, puede bloquear el ingreso de comunicaciones en modo       telefon&iacute;a y/o conexi&oacute;n directa. </li>
			<li>Los       Precios de los Contenidos Digitales ser&aacute;n los que se indiquen en el sito       de NEXTEL y en el equipo del Cliente una vez que inicie el proceso de       compra. </li>
			<li>La modalidad de contrataci&oacute;n de los       Contenidos Digitales podr&aacute; ser mediante: (i) Pago por &uacute;nica vez (uso       ilimitado); (ii) Pago mensual (Subscripci&oacute;n mensual). Ello depender&aacute; del       tipo de Contenido, sobre el cual aplicar&aacute; una u otra modalidad de pago,       siendo informado por NEXTEL al Cliente al momento en el cual este &uacute;ltimo       seleccione el Contenido que desee adquirir. </li>
			<li>La forma de pago del Contenido       Digital seleccionado depender&aacute; del plan comercial y/o modalidad       previamente contratada por el Cliente con NEXTEL, a saber: (i) si tiene       contratado un plan comercial &ldquo;pospago&rdquo;, el precio del Contenido adquirido       ser&aacute; cargado en la factura del Cliente. Bajo esta modalidad el Cliente       necesitar&aacute; ingresar el PIN MAESTRO en el proceso de compra solo en el caso       que posea mas de un equipo activo en su cuenta; (ii) si tiene contratado       un plan comercial &ldquo;STOP&rdquo; (cualesquiera de ellos), el precio del Contenido       seleccionado podr&aacute; ser&aacute; debitado, a elecci&oacute;n del Cliente, del cr&eacute;dito del       abono contratado y/o del cr&eacute;dito prepago que el Cliente hubiera activado a       trav&eacute;s de los medios de recarga habilitados; y (iii) si tiene contratado       un plan comercial prepago, el precio del Contenido seleccionado ser&aacute;       debitado &uacute;nicamente del cr&eacute;dito prepago que el Cliente hubiera activado a       trav&eacute;s de los medios de recarga habilitados. </li>
			<li>El alcance       geogr&aacute;fico de uso de los Contenidos Digitales ser&aacute; el comprendido dentro       del &aacute;rea de cobertura de la red de NEXTEL (consultar en <a href="http://www.nextel.com.ar/cobertura" title="http://www.nextel.com.ar/cobertura" target="_blank">www.nextel.com.ar/cobertura</a>). </li>
			<li>NEXTEL podr&aacute; a su       s&oacute;lo criterio en cualquier momento modificar, suspender y/o terminar por       cualquier motivo t&eacute;cnico o legal la distribuci&oacute;n de los Contenidos       Digitales, no teniendo ning&uacute;n tipo de responsabilidad por pasibles da&ntilde;os       y/o perjuicios que pudieran derivarse. </li>
			<li>NEXTEL no obstante       sus continuos esfuerzos tendientes a mejorar la calidad de los Contenidos       Digitales ofrecidos, no puede garantizar la calidad ni la precisi&oacute;n de los       mismos. NEXTEL no garantiza que (i) los resultados que los Clientes       obtengan del uso de los Contenidos Digitales responda a las expectativas       de los Clientes, (ii) la calidad de cualquier Contenido Digital adquirido       alcanzar&aacute; sus expectativas sin perjuicio de la informaci&oacute;n puesta a       disposici&oacute;n de los Clientes en relaci&oacute;n a las caracter&iacute;sticas propias de       los Contenidos Digitales ofrecidos por NEXTEL. </li>
			<li>NEXTEL no puede       ser, en ning&uacute;n caso, considerado responsable por los posibles da&ntilde;os o       p&eacute;rdidas de cualquier naturaleza que el Cliente considere que ha sufrido       como consecuencia del mal funcionamiento del Contenido Digital ofrecido en       la web o en el portal WAP del equipo, como as&iacute; tambi&eacute;n por la no recepci&oacute;n       de informaci&oacute;n y/o por su inexactitud o por ser esta incompleta. El       Cliente se sirve de los Contenidos Digitales distribuidos y propuestos a       trav&eacute;s del sitio &nbsp;de NEXTEL y en el       portal WAP del equipo bajo su propia responsabilidad y a su propio riesgo. </li>
			<li>NEXTEL no otorga       garant&iacute;as respecto al uso, acceso y adquisici&oacute;n de los Contenidos       Digitales, ni sobre ning&uacute;n software o hardware utilizado. En ning&uacute;n caso       Nextel ser&aacute; responsable por lucro cesante o da&ntilde;o emergente o por da&ntilde;o       directos o indirectos, especiales o no, ni por p&eacute;rdida econ&oacute;mica, injurias       personales o da&ntilde;os reclamados por el Cliente o cualquier tercero,       limit&aacute;ndose la responsabilidad de Nextel como m&aacute;ximo a la suma efectivamente       pagada por el uso de dichos Contenidos, salvo que la ley disponga un       tratamiento distinto. </li>
			<li>Algunos de los Contenidos Digitales       disponibles pueden incluir muestras gr&aacute;ficas, visuales y descripciones de       desnudez. Si por cualquier motivo Ud. considera que este       tipo de Contenido puede afectar su       susceptibilidad y/o no cumple con el requisito de edad requerido       (mayor de 18 a&ntilde;os), le solicitamos evitar su       descarga.</li>
			<li>Soporte t&eacute;cnico       telef&oacute;nico: de lunes a viernes (d&iacute;as h&aacute;biles) de 9 a 18 horas. NEXTEL no       brinda asistencia, atenci&oacute;n, ni soporte a domicilio. </li>
			<li>El Cliente toma       conocimiento que todos los Contenidos Digitales que adquiera quedar&aacute;n       almacenados en el equipo Nextel, por lo que si lo extrav&iacute;a o lo reemplaza,       no podr&aacute; transferirlos y tendr&iacute;a que volver a descargarlos en su nuevo       equipo desde el sitio Web arriba indicado o v&iacute;a WAP como una compra m&aacute;s.</li>
			<li>Si su equipo Nextel       no cuenta con memoria suficiente para descargar un Contenido Digital,       aparecer&aacute; en la pantalla de su equipo un aviso inform&aacute;ndole del problema.       En este caso deber&aacute; liberar un poco la memoria borrando alg&uacute;n Contenido       para que pueda intentar la descarga nuevamente.</li>
			<li>Los T&eacute;rminos y       Condiciones que surgen del presente documento as&iacute; como la relaci&oacute;n entre       el Cliente y NEXTEL ser&aacute;n regidas e interpretadas por las leyes de la       Republica Argentina. Para cualquier cuesti&oacute;n vinculada con el presente las       partes se someten a la jurisdicci&oacute;n y competencia exclusiva de los       Tribunales Federales en lo Civil y Comercial de la Ciudad de Buenos Aires       renunciando a todo otro fuero o jurisdicci&oacute;n que pudiera corresponderles. </li>
			<li>Para mayor       informaci&oacute;n ingrese a <a href="http://zona.nextel.com.ar/" target="_blank">zona.nextel.com.ar</a>&nbsp; o llame al Centro de Atenci&oacute;n al       Cliente (011) 5359-0000 o sin cargo desde su equipo Nextel al *611 o al       0800-199-0000.</li>
		</ol>
	</div>



</div>

<div id="rightNav">
	<div id="buckets">
		<div id="bucketI" style="background:url(images/cm/bg_side_nav_personalization.jpg) top left no-repeat;">
			<h2><a href='rt.jsp?c=rt&p=<%=phone%>&pn=<%=phoneName%>&u=<%=loginStatus%>'>Personalizaci&oacute;n</a></h2>
			<ul>
				<li><a href='rt.jsp?c=rt&p=<%=phone%>&pn=<%=phoneName%>&u=<%=loginStatus%>'>Ringtones</a></li>
				<li><a href='wp.jsp?c=wp&p=<%=phone%>&pn=<%=phoneName%>&u=<%=loginStatus%>'>Wallpapers</a></li>
			</ul>
		</div>
		<div id="bucketII" style="background:url(images/cm/bg_side_nav_entertainment.jpg) top left no-repeat;">
			<h2><a href='games.jsp?c=games&p=<%=phone%>&pn=<%=phoneName%>&u=<%=loginStatus%>'>Entretenimiento</a></h2>
			<ul>
				<li><a href='games.jsp?c=games&p=<%=phone%>&pn=<%=phoneName%>&u=<%=loginStatus%>'>Juegos</a></li>
			</ul>
		</div>
		<div id="bucketIII" style="background:url(images/cm/bg_side_nav_applications.jpg) top left no-repeat;">
			<h2><a href='apps.jsp?c=apps&p=<%=phone%>&pn=<%=phoneName%>&u=<%=loginStatus%>'>Aplicaciones</a></h2>
			<ul>
				<li><a href='apps.jsp?c=apps&p=<%=phone%>&pn=<%=phoneName%>&u=<%=loginStatus%>'>GPS</a></li>
				<li><a href='apps.jsp?c=apps&p=<%=phone%>&pn=<%=phoneName%>&u=<%=loginStatus%>'>Backup Agenda</a></li>
			</ul>
		</div>
	</div>
</div>
